# Generated by Django 4.2.5 on 2024-11-10 13:18

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('code', models.CharField(max_length=2, unique=True, validators=[django.core.validators.RegexValidator(message='Airline code must be exactly two uppercase letters (IATA standard)', regex='^[A-Z]{2}$')])),
                ('origin', models.CharField(max_length=150)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
