# Generated by Django 4.2.5 on 2024-11-10 13:22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('airline', '0001_initial'),
        ('airport', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=6, unique=True, validators=[django.core.validators.RegexValidator(message='Flight code must be in the format XX123 or XX123A', regex='^[A-Z]{2}\\d{1,4}[A-Z]?$')])),
                ('departure', models.TimeField()),
                ('landing', models.TimeField()),
                ('duration', models.PositiveIntegerField()),
                ('airline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='airline_flights', to='airline.airline')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flight_destinations', to='airport.airport')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flight_origins', to='airport.airport')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
